{ /*config, lib,*/ pkgs, ... }:

let
  unstable = import <nixos-unstable> { config = { allowUnfree = true; }; };
  php83 = pkgs.php83.buildEnv {
    extensions = ({ enabled, all }: enabled ++ (with all; [
      apcu
      amqp
      pcov
      redis
      xsl
    ]));
    extraConfig = ''
      apc.enabled=1
      apc.enable_cli=1
      error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
    '';
  };
  nodePackages = pkgs.nodePackages.override {
    nodejs = pkgs.nodejs_22;
  };
in
{
  environment.systemPackages = with pkgs; [
    amber
    bat
    unstable.biome
    brotli
    btop
    unstable.bun
    cargo-audit
    cargo-binstall
    cargo-expand
    cargo-generate
    cargo-info
    cargo-tarpaulin
    clipboard-jh
    cmake
    delta
    unstable.deno
    du-dust
    eza
    fastfetch
    fd
    unstable.frankenphp
    fx
    fzf
    gh
    git
    git-lfs
    gcc
    gnumake
    gnupg
    gpp
    go
    gzip
    jq
    just
    kubectl
    kubernetes
    libgcc
    lua
    man
    mdcat
    minikube
    mkpasswd
    unstable.neovim
    nixpkgs-fmt
    nodejs_22
    nodePackages.pnpm
    nodePackages.serve
    unstable.nushell
    onefetch
    openssh
    openssl_3_3
    php83
    php83.packages.composer
    php83.packages.phpstan
    php83.packages.php-cs-fixer
    php83.packages.psalm
    pkg-config
    python312Full
    python312Packages.pynvim
    python312Packages.pip
    ripgrep
    rustup
    shellcheck
    shfmt
    sqlx-cli
    starship
    stow
    stylua
    sudo
    symfony-cli
    tailspin
    taplo
    tlrc
    unstable.typos
    tokei
    topgrade
    tree-sitter
    unzip
    valkey
    viu
    wget
    xclip
    xh
    yazi
    unstable.zellij
    zip
    zoxide
    zstd
    zulu17
  ];
}
