{ /*config, lib,*/ pkgs, ... }:

let
  unstable = import <nixos-unstable> { config = { allowUnfree = true; }; };
  php83 = pkgs.php83.buildEnv {
    extensions = ({ enabled, all }: enabled ++ (with all; [
      apcu
      amqp
      pcov
      redis
      xsl
    ]));
    extraConfig = ''
      apc.enabled=1
      apc.enable_cli=1
      error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
    '';
  };
in
{
  environment.systemPackages = with pkgs; [
    amber
    bat
    unstable.biome
    brotli
    unstable.bun
    unstable.cargo-binstall
    cargo-info
    cmake
    delta
    unstable.deno
    du-dust
    fastfetch
    fd
    unstable.frankenphp
    fx
    fzf
    gh
    git
    git-lfs
    gcc
    gnumake
    gpp
    go
    gradle
    gzip
    hadolint
    htop
    jq
    just
    kubectl
    kubernetes
    libgcc
    lua
    man
    mdcat
    minikube
    mkpasswd
    unstable.neovim
    nixpkgs-fmt
    unstable.nodejs_22
    nodePackages.neovim
    nodePackages.pnpm
    nodePackages.prettier
    nodePackages.serve
    unstable.nushell
    onefetch
    openssh
    openssl_3_1
    php83
    php83.packages.composer
    php83.packages.phpstan
    php83.packages.php-cs-fixer
    php83.packages.psalm
    pkg-config
    unstable.python312Full
    unstable.python312Packages.pynvim
    unstable.python312Packages.pip
    ripgrep
    unstable.rustup
    shellcheck
    shfmt
    sqlx-cli
    starship
    stow
    stylua
    sudo
    symfony-cli
    tailspin
    taplo
    tlrc
    unstable.typos
    tokei
    unstable.topgrade
    tree-sitter
    unzip
    viu
    wget
    xclip
    xh
    yazi
    unstable.zellij
    zip
    unstable.zoxide
    zstd
    zulu17
  ];
}
