#!/usr/bin/env bash
# vim: ft=bash

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config external_bar all:40:0 \
                mouse_follows_focus off \
                focus_follows_mouse off \
                window_zoom_persist off \
                window_placement second_child \
                window_shadow float \
                window_opacity on \
                window_opacity_duration 0.2 \
                active_window_opacity 1.0 \
                normal_window_opacity 0.8 \
                window_animation_duration 0.5 \
                window_animation_easing ease_out_quint \
                insert_feedback_color 0xff9dd274 \
                split_ratio 0.50 \
                auto_balance off \
                mouse_modifier fn \
                mouse_action1 move \
                mouse_action2 resize \
                mouse_drop_action swap \
                \
                top_padding 8 \
                bottom_padding 8 \
                left_padding 8 \
                right_padding 8 \
                window_gap 10 \
                window_topmost off \
                window_border on \
                window_border_width 2 \
                layout bsp \
                active_window_border_color "0xE0808080" \
                normal_window_border_color "0x00010101" \
                insert_feedback_color "0xE02d74da"

# ===== Rules ==================================

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

echo "yabai configuration loaded.."
