#!/usr/bin/env bash
# vim: ft=bash

rgb_to_hex() {
	red_hex=$(printf '%02X' "$(awk "BEGIN {print $1 * 255}")")
	green_hex=$(printf '%02X' "$(awk "BEGIN {print $2 * 255}")")
	blue_hex=$(printf '%02X' "$(awk "BEGIN {print $3 * 255}")")

	echo "0x${red_hex}${green_hex}${blue_hex}00"
}

color_values=$(defaults read -g AppleHighlightColor)
IFS=' ' read -ra color_array <<<"$color_values"

highlight_color=$(rgb_to_hex "${color_array[0]}" "${color_array[1]}" "${color_array[2]}")

borders style=round \
	width=10.0 \
	hidpi=off \
	active_color="$highlight_color" \
	inactive_color=0xc02c2e34 \
	background_color=0x302c2e34
