command_timeout = 500

[aws]
disabled = true

[nodejs]
version_format = "v${major}.${minor}"

[php]
symbol = ' '

[container]
disabled = true

[sudo]
disabled = false

[docker_context]
detect_files = [
  'docker-compose.yaml',
  'docker-compose.yml',
  'compose.yaml',
  'compose.yml',
  'Dockerfile',
  '.dockerignore',
]
detect_extensions = ['docker', 'container', 'dockerfile', 'containerfile']
detect_folders = ['docker']
