[general]
import = ["~/.config/alacritty/base.toml"]

# working_directory = "~/dev" # doesn't work sadly

[terminal.shell]
program = "/run/current-system/sw/bin/zellij"

[font]
size = 18

[font.normal]
family = "MonaspiceNe Nerd Font Mono"
