import = ["~/.config/alacritty/base.toml"]

# working_directory = "~/dev" # doesn't work sadly

[shell]
program = "/usr/local/bin/zellij"

[font]
size = 16

[font.normal]
family = "MonaspiceNe Nerd Font Mono"
