import = ["~/.config/alacritty/base.toml"]

## wip native zellij on windows
# shell.program = "D:\\dev\\zellij\\target\\release\\zellij.exe"
# working_directory = "D:\\dev"

[shell]
program = "C:\\Windows\\system32\\wsl.exe"
args = ["--cd", "/home/zuruh/", "--", "/run/current-system/sw/bin/zellij"]
# args = [
#   "--cd",
#   "/home/zuruh",
#   "-u",
#   "zuruh",
#   "--",
#   "/home/zuruh/.cargo/bin/zellij",
# ]

[env]
XDG_CONFIG_HOME = "/home/zuruh/.config"

[font]
size = 12

[font.normal]
family = "MonaspiceNe Nerd Font"

[[keyboard.bindings]]
key = "v"
mods = "Control"
action = "Paste"

[[keyboard.bindings]]
key = "Play"
action = "None"

[[keyboard.bindings]]
key = "Pause"
action = "None"

[[keyboard.bindings]]
key = "Play"
action = "None"

[[keyboard.bindings]]
key = "MediaPlay"
action = "None"

[[keyboard.bindings]]
key = "MediaPause"
action = "None"

[[keyboard.bindings]]
key = "MediaPlayPause"
action = "None"

[[keyboard.bindings]]
key = "AudioVolumeDown"
action = "None"

[[keyboard.bindings]]
key = "AudioVolumeUp"
action = "None"

[[keyboard.bindings]]
key = "AudioVolumeMute"
action = "None"

[[keyboard.bindings]]
key = "MediaTrackNext"
action = "None"

[[keyboard.bindings]]
key = "MediaTrackPrevious"
action = "None"

[[keyboard.bindings]]
key = "ScrollLock"
action = "None"
