import = ["~/.config/alacritty/base.toml"]

[shell]
program = "C:\\Windows\\system32\\wsl.exe"
args = [
  "--cd",
  "/home/zuruh",
  "-u",
  "zuruh",
  "--",
  "/home/zuruh/.cargo/bin/zellij",
  "-l",
  "compact",
]

[font.normal]
family = "MonaspiceNe Nerd Font"
